language: go

go:
  - 1.14

env:
  - GO111MODULE=on

services:
  - docker

script: make travis

deploy:
  - provider: releases
    api_key:
      secure: bvkjSM21v4DW47ShamvpXAZF7wcrSdpCytjV0Ehod9Rc6DT3cZbzI07BDZhXUwtnl/fPbMNLWETtxKh/3htv14sFQGO/r2InTQOV3+mO/hxrMGiCugneYHWld2nwRUsVK0Dnt14hBzTecGAMdffRmdjhUJGMCJZMLy6dKpsoLBHuQva5XA6edx/YlRgxbs/y/t5zNE0OTPsh+KTPqabt5PKRqxhIhJbvMc2UGJN4zSQD2HHEe5fwGJ9A3Wkqo6zyhs+7wbgc8oBbBpTEsOlD7MB6c86dSNSm/o1WybFknlZYJpcqCQSeysCDPogFMOy2C8S2pANm0YqXic2UlWaWfnFjC51WaP7D9GT5m5ed/betXIeefLqUQU+6oIC5Up0K8p6nPCDABif7PxJDVe80nm+bcpE3UAhos4CDuOFPz2wYC8/muA8CaTSs7EGN4iiGxgdgpcpZxlF33NmnvhzloYgZlkgmGHnQH6GU/w8nmpWsm+8fckzITRu4t3kpTGlpDmCDlU2dQ6TDJwUKJOJe/6r/XT5Cljk1MNecmF182XbgfnVYki597IdBh0Go7lQM2OvfRdYh0LMcJap93U4dPuDxm6oAoXvsShgOV5TjkJJzMx0qiVnnFuNVixux5GNpubMd0HY8tjIbqcGCTx8OXt6aKiJIgqzJQEK+bVum6rI=
    file: etcd-bootstrap
    skip_cleanup: true
    on:
      repo: sky-uk/etcd-bootstrap
      tags: true
  - provider: script
    script: make release
    on:
      tags: true
